<h1>Liste des Meetups</h1>

<ul>
<?php foreach($meetups as $meetup): /* @var $meetup \Application\Entity\Meetup */ ?>

    <h3>
        <a href="#">
            <?= $this->escapeHtml($meetup->getTitre()); ?>
        </a>
    </h3>

    <p>
        <?= $this->escapeHtml($meetup->getDescription()); ?>
    </p>

<?php endforeach; ?>
</ul>

<a href="<?= $this->url('meetups/add'); ?>" class="btn btn-primary">Add new</a>