<h1>Liste des Meetups</h1>

<ul>
<?php foreach($meetups as $meetup): /* @var $meetup \Application\Entity\Meetup */ ?>

    <h3>
        <a href="#">
            <?= $this->escapeHtml($meetup->getTitre()); ?>
        </a>
    </h3>

    <p>
        <?= $this->escapeHtml($meetup->getDescription()); ?>
    </p>
    <p>
        Date de début : <?= $this->escapeHtml($meetup->getDatedeb()); ?>
    </p>
    <p>
        Date de fin : <?= $this->escapeHtml($meetup->getDescrgetDatefin()); ?>
    </p>
<?php endforeach; ?>
</ul>

<a href="<?= $this->url('add'); ?>" class="btn btn-primary">Ajouter un nouveau Meetup</a>